const areaHashes: Record<string, string> = {
  [GetHashKey("AIRP")]: "Los Santos International Airport",
  [GetHashKey("ALAMO")]: "Alamo Sea",
  [GetHashKey("ALTA")]: "Alta",
  [GetHashKey("ARMYB")]: "Fort Zancudo",
  [GetHashKey("BANHAMC")]: "Banham Canyon Dr",
  [GetHashKey("BANNING")]: "Banning",
  [GetHashKey("BEACH")]: "Vespucci Beach",
  [GetHashKey("BHAMCA")]: "Banham Canyon",
  [GetHashKey("BRADP")]: "Braddock Pass",
  [GetHashKey("BRADT")]: "Braddock Tunnel",
  [GetHashKey("BURTON")]: "Burton",
  [GetHashKey("CALAFB")]: "Calafia Bridge",
  [GetHashKey("CANNY")]: "Raton Canyon",
  [GetHashKey("CCREAK")]: "Cassidy Creek",
  [GetHashKey("CHAMH")]: "Chamberlain Hills",
  [GetHashKey("CHIL")]: "Vinewood Hills",
  [GetHashKey("CHU")]: "Chumash",
  [GetHashKey("CMSW")]: "Chiliad Mountain State Wilderness",
  [GetHashKey("CYPRE")]: "Cypress Flats",
  [GetHashKey("DAVIS")]: "Davis",
  [GetHashKey("DELBE")]: "Del Perro Beach",
  [GetHashKey("DELPE")]: "Del Perro",
  [GetHashKey("DELSOL")]: "La Puerta",
  [GetHashKey("DESRT")]: "Grand Senora Desert",
  [GetHashKey("DOWNT")]: "Downtown",
  [GetHashKey("DTVINE")]: "Downtown Vinewood",
  [GetHashKey("EAST_V")]: "East Vinewood",
  [GetHashKey("EBURO")]: "El Burro Heights",
  [GetHashKey("ELGORL")]: "El Gordo Lighthouse",
  [GetHashKey("ELYSIAN")]: "Elysian Island",
  [GetHashKey("GALFISH")]: "Galilee",
  [GetHashKey("GOLF")]: "GWC and Golfing Society",
  [GetHashKey("GRAPES")]: "Grapeseed",
  [GetHashKey("GREATC")]: "Great Chaparral",
  [GetHashKey("HARMO")]: "Harmony",
  [GetHashKey("HAWICK")]: "Hawick",
  [GetHashKey("HORS")]: "Vinewood Racetrack",
  [GetHashKey("HUMLAB")]: "Humane Labs and Research",
  [GetHashKey("JAIL")]: "Bolingbroke Penitentiary",
  [GetHashKey("KOREAT")]: "Little Seoul",
  [GetHashKey("LACT")]: "Land Act Reservoir",
  [GetHashKey("LAGO")]: "Lago Zancudo",
  [GetHashKey("LDAM")]: "Land Act Dam",
  [GetHashKey("LEGSQU")]: "Legion Square",
  [GetHashKey("LMESA")]: "La Mesa",
  [GetHashKey("LOSPUER")]: "La Puerta",
  [GetHashKey("MIRR")]: "Mirror Park",
  [GetHashKey("MORN")]: "Morningwood",
  [GetHashKey("MOVIE")]: "Richards Majestic",
  [GetHashKey("MTCHIL")]: "Mount Chiliad",
  [GetHashKey("MTGORDO")]: "Mount Gordo",
  [GetHashKey("MTJOSE")]: "Mount Josiah",
  [GetHashKey("MURRI")]: "Murrieta Heights",
  [GetHashKey("NCHU")]: "North Chumash",
  [GetHashKey("NOOSE")]: "N.O.O.S.E",
  [GetHashKey("OCEANA")]: "Pacific Ocean",
  [GetHashKey("PALCOV")]: "Paleto Cove",
  [GetHashKey("PALETO")]: "Paleto Bay",
  [GetHashKey("PALFOR")]: "Paleto Forest",
  [GetHashKey("PALHIGH")]: "Palomino Highlands",
  [GetHashKey("PALMPOW")]: "Palmer-Taylor Power Station",
  [GetHashKey("PBLUFF")]: "Pacific Bluffs",
  [GetHashKey("PBOX")]: "Pillbox Hill",
  [GetHashKey("PROCOB")]: "Procopio Beach",
  [GetHashKey("RANCHO")]: "Rancho",
  [GetHashKey("RGLEN")]: "Richman Glen",
  [GetHashKey("RICHM")]: "Richman",
  [GetHashKey("ROCKF")]: "Rockford Hills",
  [GetHashKey("RTRAK")]: "Redwood Lights Track",
  [GetHashKey("SANAND")]: "San Andreas",
  [GetHashKey("SANCHIA")]: "San Chianski Mountain Range",
  [GetHashKey("SANDY")]: "Sandy Shores",
  [GetHashKey("SKID")]: "Mission Row",
  [GetHashKey("SLAB")]: "Stab City",
  [GetHashKey("STAD")]: "Maze Bank Arena",
  [GetHashKey("STRAW")]: "Strawberry",
  [GetHashKey("TATAMO")]: "Tataviam Mountains",
  [GetHashKey("TERMINA")]: "Terminal",
  [GetHashKey("TEXTI")]: "Textile City",
  [GetHashKey("TONGVAH")]: "Tongva Hills",
  [GetHashKey("TONGVAV")]: "Tongva Valley",
  [GetHashKey("VCANA")]: "Vespucci Canals",
  [GetHashKey("VESP")]: "Vespucci",
  [GetHashKey("VINE")]: "Vinewood",
  [GetHashKey("WINDF")]: "Ron Alternates Wind Farm",
  [GetHashKey("WVINE")]: "West Vinewood",
  [GetHashKey("ZANCUDO")]: "Zancudo River",
  [GetHashKey("ZP_ORT")]: "Port of South Los Santos",
  [GetHashKey("ZQ_UAR")]: "Davis Quartz",
};

export function getZone(position: [number, number, number]) {
  const areaHash = GetHashKey(GetNameOfZone(...position));
  return areaHashes[areaHash];
}
